Kztek_Web/Controllers/SY_MenuFunctionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Kztek_Web.Models;
using Kztek_Model.Models;
using Kztek_Library.Helpers;
using Kztek_Web.Attributes;
using Kztek_Service.Admin.Interfaces;

namespace Kztek_Web.Controllers
{
    public class SY_MenuFunctionController : Controller
    {
        private ISY_MenuFunctionService _SY_MenuFunctionService;
        public SY_MenuFunctionController(ISY_MenuFunctionService _SY_MenuFunctionService)
        {
            this._SY_MenuFunctionService = _SY_MenuFunctionService;
        }

        [CheckSessionCookie]
        public async Task<IActionResult> Index()
        {
            var data = await _SY_MenuFunctionService.GetAll();

            return View(data.ToList());
        }

        // public PartialViewResult SubMenu(List<SY_MenuFunction> listChild, List<SY_MenuFunction> allFunction)
        // {
        //     var model = new SY_MenuFunction_Tree()
        //     {
        //         Data_All = allFunction,
        //         Data_Child = listChild
        //     };

        //     return PartialView(model);
        // }

        [CheckSessionCookie]
        [HttpGet]
        public async Task<IActionResult> Create(SY_MenuFunction_Submit model)
        {

            model = model == null ? new SY_MenuFunction_Submit() : model;
            model.Active = true;

            ViewBag.Data_MenuFunction = await GetMenuList();
            ViewBag.Data_MenuType = StaticList.MenuType();

            return View(model);
        }

        [CheckSessionCookie]
        [HttpPost]
        public async Task<IActionResult> Create(SY_MenuFunction_Submit model, bool SaveAndCountinue = false)
        {
            ViewBag.Data_MenuFunction = await GetMenuList();
            ViewBag.Data_MenuType = StaticList.MenuType();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //Gán giá trị
            var id = Guid.NewGuid().ToString();

            model.ControllerName = !string.IsNullOrWhiteSpace(model.ControllerName) ? model.ControllerName.Trim() : string.Format("Controller_{0}", id);
            model.ActionName = !string.IsNullOrWhiteSpace(model.ActionName) ? model.ActionName.Trim() : string.Format("Action_{0}", id);

            var obj = new SY_MenuFunction()
            {
                Id = id,
                MenuName = model.MenuName,
                ControllerName = model.ControllerName,
                ActionName = model.ActionName,
                Icon = model.Icon,
                MenuType = model.MenuType,
                ParentId = string.IsNullOrWhiteSpace(model.ParentId) ? "" : model.ParentId,
                Active = model.Active,
                SortOrder = model.SortOrder,
                DateCreated = DateTime.Now,
            };

            //Thực hiện thêm mới
            var result = await _SY_MenuFunctionService.Create(obj);
            if (result.isSuccess)
            {
                if (SaveAndCountinue)
                {
                    TempData["Success"] = "Thêm mới thành công";
                    return RedirectToAction("Create", new { ControllerName = obj.ControllerName, ParentId = obj.ParentId, MenuType = obj.MenuType });
                }

                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", result.Message);
                return View(obj);
            }
        }

        [CheckSessionCookie]
        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
            var model = await _SY_MenuFunctionService.GetCustomById(id);

            ViewBag.Data_MenuFunction = await GetMenuList();
            ViewBag.Data_MenuType = StaticList.MenuType();

            return View(model);
        }

        [CheckSessionCookie]
        [HttpPost]
        public async Task<IActionResult> Update(SY_MenuFunction_Submit model)
        {
            ViewBag.Data_MenuFunction = await GetMenuList();
            ViewBag.Data_MenuType = StaticList.MenuType();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var oldObj = await _SY_MenuFunctionService.GetById(model.Id);
            if (oldObj == null)
            {
                ModelState.AddModelError("", "Bản ghi không tồn tại");
                return View(model);
            }

            model.ControllerName = !string.IsNullOrWhiteSpace(model.ControllerName) ? model.ControllerName.Trim() : string.Format("Controller_{0}", model.Id);
            model.ActionName = !string.IsNullOrWhiteSpace(model.ActionName) ? model.ActionName.Trim() : string.Format("Action_{0}", model.Id);

            oldObj.MenuName = model.MenuName;
            oldObj.ControllerName = model.ControllerName.Trim();
            oldObj.ActionName = model.ActionName.Trim();
            oldObj.ParentId = string.IsNullOrWhiteSpace(model.ParentId) ? "" : model.ParentId;
            oldObj.Active = model.Active;
            oldObj.Icon = model.Icon;
            oldObj.MenuType = model.MenuType;
            oldObj.SortOrder = model.SortOrder;

            var result = await _SY_MenuFunctionService.Update(oldObj);
            if (result.isSuccess)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", result.Message);
                return View(model);
            }
        }

        [CheckSessionCookie]
        public async Task<IActionResult> Delete(string id)
        {
            var result = await _SY_MenuFunctionService.Delete(id);

            return Json(result);
        }

        private async Task<List<SY_MenuFunction_Submit>> GetMenuList()
        {
            var list = new List<SY_MenuFunction_Submit>
            {
                new SY_MenuFunction_Submit {  Id = "", MenuName = "- Chọn danh mục -" }
            };

            var MenuList = await _SY_MenuFunctionService.GetAllCustomActiveOrder();
            var parent = MenuList.Where(c => c.ParentId == "").ToList();
            if (parent.Any())
            {
                foreach (var item in parent)
                {
                    //Nếu có thì duyệt tiếp để lưu vào list
                    list.Add(new SY_MenuFunction_Submit { Id = item.Id, MenuName = item.MenuName });

                    var listChild = MenuList.Where(c => c.ParentId == item.Id).ToList();

                    //Gọi action để lấy danh sách submenu theo id
                    if (listChild.Any())
                    {
                        Children(listChild, MenuList, list, item);
                    }

                    list.Add(new SY_MenuFunction_Submit { Id = "", MenuName = "-----" });

                }
            }
            return list;
        }

        private void Children(List<SY_MenuFunction_Submit> listChild, List<SY_MenuFunction_Submit> allFunction, List<SY_MenuFunction_Submit> lst, SY_MenuFunction_Submit itemParent)
        {
            //Kiểm tra có dữ liệu chưa
            if (listChild.Any())
            {
                foreach (var item in listChild)
                {
                    //Nếu có thì duyệt tiếp để lưu vào list
                    lst.Add(new SY_MenuFunction_Submit { Id = item.Id, MenuName = itemParent.MenuName + " \\ " + item.MenuName });

                    //Gọi action để lấy danh sách submenu theo id
                    var child = allFunction.Where(c => c.ParentId == item.Id).ToList();

                    //Gọi action để lấy danh sách submenu theo id
                    if (child.Any())
                    {
                        item.MenuName = itemParent.MenuName + " \\ " + item.MenuName;
                        Children(child, allFunction, lst, item);
                    }
                }
            }
        }
    }
}

Kztek_Web/Controllers/SY_RoleController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Kztek_Web.Models;
using Kztek_Model.Models;
using Kztek_Library.Helpers;
using Kztek_Web.Attributes;
using Kztek_Service.Admin.Interfaces;

namespace Kztek_Web.Controllers
{
    public class SY_RoleController : Controller
    {
        private ISY_RoleService _SY_RoleService;
        private ISY_MenuFunctionService _SY_MenuFunctionService;

        public SY_RoleController(ISY_RoleService _SY_RoleService, ISY_MenuFunctionService _SY_MenuFunctionService)
        {
            this._SY_RoleService = _SY_RoleService;
            this._SY_MenuFunctionService = _SY_MenuFunctionService;
        }

        [CheckSessionCookie]
        public async Task<IActionResult> Index()
        {
            var list = await _SY_RoleService.GetAll();

            ViewBag.AuthValue = await AuthHelper.CheckAuthAction("SY_Role", this.HttpContext);

            return View(list.ToList());
        }

        [CheckSessionCookie]
        [HttpGet]
        public async Task<IActionResult> Create(SY_Role_Submit model)
        {
            model = model == null ? new SY_Role_Submit() : model;
            model.Data_Tree = await _SY_MenuFunctionService.GetAllActive();

            return View(model);
        }

        [CheckSessionCookie]
        [HttpPost]
        public async Task<IActionResult> Create(SY_Role_Submit model, bool SaveAndCountinue = false)
        {
            model.Data_Tree = await _SY_MenuFunctionService.GetAllActive();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var obj = new SY_Role()
            {
                RoleName = model.RoleName,
                Description = model.Description,
                Active = model.Active,
                Id = Guid.NewGuid().ToString()
            };

            if (!string.IsNullOrWhiteSpace(model.MenuFunctionIds))
            {
                var ks = model.MenuFunctionIds.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries);
                model.MenuFunctions = new List<string>();
                foreach (var item in ks)
                {
                    model.MenuFunctions.Add(item);
                }

                foreach (var item in model.MenuFunctions)
                {
                    var t = new SY_Map_Role_Menu()
                    {
                        Id = Guid.NewGuid().ToString(),
                        MenuId = item,
                        RoleId = obj.Id
                    };

                    await _SY_MenuFunctionService.CreateMap(t);
                }
            }

            //Thực hiện thêm mới
            var result = await _SY_RoleService.Create(obj);
            if (result.isSuccess)
            {
                if (SaveAndCountinue)
                {
                    TempData["Success"] = "Thêm mới thành công";
                    return RedirectToAction("Create");
                }

                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", result.Message);
                return View(obj);
            }
        }

        [CheckSessionCookie]
        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
            var model = await _SY_RoleService.GetCustomById(id);
            model.Data_Tree = await _SY_MenuFunctionService.GetAllActive();

            return View(model);
        }

        [CheckSessionCookie]
        [HttpPost]
        public async Task<IActionResult> Update(SY_Role_Submit model)
        {
            model.Data_Tree = await _SY_MenuFunctionService.GetAllActive();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var oldObj = await _SY_RoleService.GetById(model.Id);
            if (oldObj == null)
            {
                ModelState.AddModelError("", "Bản ghi không tồn tại");
                return View(model);
            }

            oldObj.Active = model.Active;
            oldObj.Description = model.Description;
            oldObj.RoleName = model.RoleName;

            //Cập nhật lại menu
            await _SY_MenuFunctionService.DeleteMap(oldObj.Id);

            if (!string.IsNullOrWhiteSpace(model.MenuFunctionIds))
            {
                var ks = model.MenuFunctionIds.Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries);
                model.MenuFunctions = new List<string>();
                foreach (var item in ks)
                {
                    model.MenuFunctions.Add(item);
                }

                foreach (var item in model.MenuFunctions)
                {
                    var t = new SY_Map_Role_Menu()
                    {
                        Id = Guid.NewGuid().ToString(),
                        MenuId = item,
                        RoleId = oldObj.Id
                    };

                    await _SY_MenuFunctionService.CreateMap(t);
                }
            }

            var result = await _SY_RoleService.Update(oldObj);
            if (result.isSuccess)
            {
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", result.Message);
                return View(model);
            }
        }

        [CheckSessionCookie]
        public async Task<IActionResult> Delete(string id)
        {
            var result = await _SY_RoleService.Delete(id);

            return Json(result);
        }
    }
}

Kztek_Web/Views/SY_Role/Create.cshtml
@model Kztek_Model.Models.SY_Role_Submit

@{
ViewBag.Title = "Thêm mới vai trò";
    var menus = (List<string>)ViewBag.MenuFunctions;

}

<div class="page-header">
    <h1>
        @ViewBag.Title
    </h1>
</div>

<div class="row">
    @if (TempData["Success"] != null) {
    <strong style="color:green">@TempData["Success"]</strong>
    }
    <strong style="color:red">@ViewBag.Error</strong>
</div>

<div class="row">

    @using (Html.BeginForm("Create", "SY_Role", FormMethod.Post, new { encType = "multipart/form-data", @class =
    "form-horizontal", @role = "form", @id="frmRole" }))
    {

    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    @Html.HiddenFor(n => n.MenuFunctionIds)
    @Html.Hidden("SaveAndCountinue", false)

    <div class="col-xs-7">
        <div class="form-group">
            <label class="col-sm-4 control-label no-padding-right">
                Tên vai trò <span style="color:red">*</span></label>
            <div class="col-sm-6 col-xs-12">
                @Html.TextBoxFor(n => n.RoleName, new { @class = "form-control",
                @placeholder = "Tên vai trò" }) @Html.ValidationMessageFor(n =>
                n.RoleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label no-padding-right"> Mô tả </label>
            <div class="col-sm-6 col-xs-12">
                @Html.TextAreaFor(n => n.Description, new { @class = "form-control",
                @placeholder = "Mô tả" }) @Html.ValidationMessageFor(n =>
                n.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label no-padding-right"> Kích hoạt </label>
            <div class="col-sm-8">
                <label class="line-height-250">
                    @Html.CheckBoxFor(n => n.Active, new { @class = "ace" })
                    <span class="lbl"></span>
                </label>
            </div>
        </div>
    </div>

    <div class="col-xs-5">
        @await Html.PartialAsync("MenuFunctionParent", new Kztek_Model.Models.SY_Role_Selected() {
            Data_Tree = Model.Data_Tree,
            Selected = Model.MenuFunctions
        })
    </div>

     @await Html.PartialAsync("~/Views/Shared/Partials/ButtonPartial.cshtml", new Kztek_Library.Models.AuthPartialModel() {
          ControllerName = "SY_Role",
          ActionName = "Create",
          RecordId = "",
          model = null,
          Auth_Value = null
      })
    }
</div>

@section scripts{
<script>
    $(document).ready(function () {
        $("#Countinue").click(function () {
            $("#SaveAndCountinue").val("true");
        });

            $(".chkCheckBox").click(function() {
                var cmd = $(this);
                cmd.parent().parent().find('ul li input[type=checkbox]').prop('checked', cmd.is(':checked'));
            });

            $("span.liMenuFunction").click(function() {
                var cmd = $(this);
                cmd.parent().find('ul li span.liMenuFunction').parent().parent().fadeToggle();
            });

           $("#frmRole").submit(function () {
                var lstId = "";

                $("input[name='chkCheckBox']").each(function() {
                    var cmd = $(this);
                    var id = cmd.prop("value");

                    if ($(this).is(":checked")) {
                        lstId = lstId + id + ";";
                    }
                });

                $("#MenuFunctionIds").val(lstId);
            }); 
    });
</script>
}

Kztek_Web/Views/SY_Role/Index.cshtml
@model List<Kztek_Model.Models.SY_Role>

@{
    ViewBag.Title = "Danh sách vai trò";
     var authModel = (Kztek_Library.Models.AuthActionModel)ViewBag.AuthValue;
}

<div class="page-header">
    <h1>
       @ViewBag.Title
    </h1>
</div>

<div class="row">
    <div class="col-xs-12">
            @await Html.PartialAsync("~/Views/Shared/Partials/ActionPartial.cshtml", new Kztek_Library.Models.AuthPartialModel() {
                ControllerName = "SY_Role",
                ActionName = "Create",
                RecordId = "",
                model = null,
                Auth_Value = authModel
            })
    </div>
</div>

<div class="hr hr-18 dotted hr-24"></div>

<div class="row">
    <div class="col-xs-12">
        <table class="table  table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-left">Tên vai trò</th>
                    <th class="text-left">Mô tả</th>
                    <th class="text-left">Trạng thái</th>
                    <th class="text-left">Xử lý</th>
                </tr>
            </thead>

            <tbody>
                @if (Model.Any())
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td class="text-left">
                                @item.RoleName
                            </td>

                            <td class="text-left">
                                @item.Description
                            </td>

                            <td class="center">
                                @if (item.Active == true)
                                {
                                    <span class="label label-sm label-success">Kích hoạt</span>
                                }
                                else
                                {
                                    <span class="label label-sm label-warning">Chưa kích hoạt</span>
                                }
                            </td>
                            <td class="center">
                                <div class="btn-group">
                                    @await Html.PartialAsync("~/Views/Shared/Partials/ActionPartial.cshtml", new Kztek_Library.Models.AuthPartialModel() {
                ControllerName = "SY_Role",
                ActionName = "Update",
                RecordId = "",
                model = new { id = item.Id },
                Auth_Value = authModel
            })


                                          @await Html.PartialAsync("~/Views/Shared/Partials/ActionPartial.cshtml", new Kztek_Library.Models.AuthPartialModel() {
                ControllerName = "SY_Role",
                ActionName = "Delete",
                RecordId = item.Id,
                model = null,
                Auth_Value = authModel
            })
                                </div>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function() {
            $(".btnDelete").click(function() {
                var cmd = $(this);
                var id = cmd.attr('idata');

                bootbox.confirm("Bạn chắc chắn muốn xóa?", function(result){
                    if (result) {
                        JSHelper.AJAX_Delete('/SY_Role/Delete', id)
                        .success(function(response) {
                           if(response.isSuccess) {
                               cmd.parent().parent().parent().fadeOut();
                                toastr.success('Xóa thành công', 'Thông báo')
                           } else {
                               toastr.error(response.Message)
                           }
                        });
                    }
                })
            });
        });
    </script>
}

Kztek_Web/Views/SY_Role/MenuFunctionChild.cshtml
@model Kztek_Model.Models.SY_Role_Selected

@{
}

@if (Model.Data_Child.Any())
{
    <ul class="submenufunction">
        @foreach (var item in Model.Data_Child.OrderBy(n => n.SortOrder))
        {
            var childItem = Model.Data_Tree.Where(c => c.ParentId == item.Id).ToList();
            <li>
                <label style="margin-bottom: 0px;">
                    <input type="checkbox" name="chkCheckBox" id="chkCheckBox" value="@item.Id" class="ace chkCheckBox" @string.Format("{0}", Model.Selected.Contains(item.Id) ? "checked" : "" )/>
                    <span class="lbl"></span>
                </label>
                <span class="liMenuFunction" style="color: #666;">
                    @if (item.Active)
                    {
                        <span>@item.SortOrder</span> <span>. @item.MenuName</span>
                    }
                    else
                    {
                        <span style="text-decoration:line-through">
                            <span>@item.SortOrder</span> <span>. @item.MenuName</span>
                        </span>
                    }
                </span>
                 <span>
                             <a href='@Url.Action("Update", "SY_MenuFunction", new { id = item.Id })'>
                                 <i class="ace-icon fa fa-pencil-square-o"></i>
                             </a>
                         </span>
                
                @if (childItem.Any())
                {
                    @await Html.PartialAsync("MenuFunctionChild", new Kztek_Model.Models.SY_Role_Selected() {
                        Data_Tree = Model.Data_Tree,
                        Selected = Model.Selected,
                        Data_Child = childItem
                    })
                }
                
            </li>
        }
    </ul>
}

Kztek_Web/Views/SY_Role/MenuFunctionParent.cshtml
@model Kztek_Model.Models.SY_Role_Selected

<ul class="treeCustom">
            @if (Model.Data_Tree.Any())
            {
                var listParent = Model.Data_Tree.Where(c => c.ParentId == "");
                foreach (var item in listParent)
                 {
                     var childItem = Model.Data_Tree.Where(c => c.ParentId == item.Id).ToList();
                     <li>
                         <label style="margin-bottom: 0px;">
                             <input type="checkbox" name="chkCheckBox" id="chkCheckBox" value="@item.Id" class="ace chkCheckBox" @string.Format("{0}", Model.Selected.Contains(item.Id) ? "checked" : "" )/>
                             <span class="lbl"></span>
                         </label>
                         <span class="liMenuFunction" style="font-weight: 700; color: #333;">
                             <span>@item.SortOrder</span>
                                 <span>. @item.MenuName</span>
                         </span>
                        
                         @if (childItem.Any())
                        {
                            @await Html.PartialAsync("MenuFunctionChild", new Kztek_Model.Models.SY_Role_Selected() {
                                Data_Tree = Model.Data_Tree,
                                Selected = Model.Selected,
                                Data_Child = childItem
                            })
                        }

                     </li>
                 }
            }

            
        </ul>

Kztek_Web/Views/SY_Role/Update.cshtml
@model Kztek_Model.Models.SY_Role_Submit

@{
ViewBag.Title = "Cập nhật vai trò";
}

<div class="page-header">
    <h1>
        @ViewBag.Title
    </h1>
</div>

<div class="row">
    @if (TempData["Success"] != null) {
    <strong style="color:green">@TempData["Success"]</strong>
    }
    <strong style="color:red">@ViewBag.Error</strong>
</div>

<div class="row">

    @using (Html.BeginForm("Update", "SY_Role", FormMethod.Post, new { encType = "multipart/form-data", @class =
    "form-horizontal", @role = "form", @id="frmRole" }))
    {

    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    @Html.HiddenFor(n => n.MenuFunctionIds)
    @Html.HiddenFor(n => n.Id)

    <div class="col-xs-7">
        <div class="form-group">
            <label class="col-sm-4 control-label no-padding-right">
                Tên vai trò <span style="color:red">*</span></label>
            <div class="col-sm-6 col-xs-12">
                @Html.TextBoxFor(n => n.RoleName, new { @class = "form-control",
                @placeholder = "Tên vai trò" }) @Html.ValidationMessageFor(n =>
                n.RoleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label no-padding-right"> Mô tả </label>
            <div class="col-sm-6 col-xs-12">
                @Html.TextAreaFor(n => n.Description, new { @class = "form-control",
                @placeholder = "Mô tả" }) @Html.ValidationMessageFor(n =>
                n.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label no-padding-right"> Kích hoạt </label>
            <div class="col-sm-8">
                <label class="line-height-250">
                    @Html.CheckBoxFor(n => n.Active, new { @class = "ace" })
                    <span class="lbl"></span>
                </label>
            </div>
        </div>
    </div>

    <div class="col-xs-5">
        @await Html.PartialAsync("MenuFunctionParent", new Kztek_Model.Models.SY_Role_Selected() {
            Data_Tree = Model.Data_Tree,
            Selected = Model.MenuFunctions
        })
    </div>

   @await Html.PartialAsync("~/Views/Shared/Partials/ButtonPartial.cshtml", new Kztek_Library.Models.AuthPartialModel() {
          ControllerName = "SY_Role",
          ActionName = "Update",
          RecordId = "",
          model = null,
          Auth_Value = null
      })
    }
</div>

@section scripts{
<script>
    $(document).ready(function () {
        $("#Countinue").click(function () {
            $("#SaveAndCountinue").val("true");
        });

            $(".chkCheckBox").click(function() {
                var cmd = $(this);
                cmd.parent().parent().find('ul li input[type=checkbox]').prop('checked', cmd.is(':checked'));
            });

            $("span.liMenuFunction").click(function() {
                var cmd = $(this);
                cmd.parent().find('ul li span.liMenuFunction').parent().parent().fadeToggle();
            });

           $("#frmRole").submit(function () {
                var lstId = "";

                $("input[name='chkCheckBox']").each(function() {
                    var cmd = $(this);
                    var id = cmd.prop("value");

                    if ($(this).is(":checked")) {
                        lstId = lstId + id + ";";
                    }
                });

                $("#MenuFunctionIds").val(lstId);
            }); 
    });
</script>
}