Kztek_Web/Components/Language/LanguageViewComponent.cs
using Kztek_Library.Helpers;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kztek_Web.Components.Language
{
    public class LanguageViewComponent : ViewComponent
    {
        public LanguageViewComponent()
        {
        }

        public async Task<IViewComponentResult> InvokeAsync(string path)
        {
            var text = await LanguageHelper.GetLanguageText(path);
            ViewBag.Text = text;
            return View();
        }
    }
}

Kztek_Web/Components/Website/WebsiteViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kztek_Library.Helpers;
using Kztek_Library.Models;
using Kztek_Service.Admin;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Kztek_Web.Components.Breadcrumb
{
    public class WebsiteViewComponent : ViewComponent
    {
        public WebsiteViewComponent()
        {
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new WebsiteModel()
            {
                WebsiteName = await Kztek_Library.Helpers.AppSettingHelper.GetStringFromAppSetting("WebConfig:WebsiteName")
            };

            return View(model);
        }
    }
}

Kztek_Web/Views/Shared/Partials/ActionPartial.cshtml
@model Kztek_Library.Models.AuthPartialModel

<!-- Create -->
@if(Model.Auth_Value.Create_Auth == 1 && Model.ActionName == "Create") 
{
    <a href='@Url.Action("Create", Model.ControllerName, Model.model)' class="btn btn-white btn-success">
        <i class=" fa fa-plus"></i> Thêm mới
    </a>
}

@if(Model.Auth_Value.Update_Auth == 1 && Model.ActionName == "Update") 
{
    <a href='@Url.Action("Update", Model.ControllerName, Model.model)' class="green" title="Cập nhật">
        <i class="ace-icon fa fa-pencil bigger-120"></i>
    </a>
}

@if(Model.Auth_Value.Delete_Auth == 1 && Model.ActionName == "Delete") 
{
    <a href="javascript:void(0)" class="btnDelete red" idata="@Model.RecordId" title="Xóa">
        <i class="ace-icon fa fa-trash bigger-120"></i>
    </a>
}

@if(Model.ActionName == "Export") 
{
    <a href="javascript:void(0)" class="btnExport btn btn-white btn-primary" title="Xuất excel">
                <i class="ace-icon fa fa-file-excel-o"></i> Xuất excel
            </a>
}
 


                                        

Kztek_Web/Views/Shared/Partials/ButtonPartial.cshtml
@model Kztek_Library.Models.AuthPartialModel

@if (Model.ActionName == "Create")
{
    <div class="ace-settings-container" id="ace-settings-container" style="position: fixed; top: 155px;">
        <div class="btn btn-app btn-xs btn-grey ace-settings-btn open" id="ace-settings-btn">
            <i class="ace-icon fa fa-cog bigger-130"></i>
        </div>

        <div class="ace-settings-box clearfix open" id="ace-settings-box">
            <!-- /.pull-left -->
            <div class="bg-rightbox">
                <div class="clearfix lineButton">
                    <div class="col-md-12 input-group">
                        <button class="btn btn-success" type="submit" id="Countinue">
                            <i class="ace-icon fa fa-refresh bigger-110"></i>
                            @await Component.InvokeAsync("Language", new { path = "BODY:BUTTON:SAVE" })
                        </button>
                        <button class="btn btn-info" type="submit">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            @await Component.InvokeAsync("Language", new { path = "BODY:BUTTON:COMPLETED" })
                        </button>
                        <button class="btn btnReset" type="reset">
                            <i class="ace-icon fa fa-undo bigger-110"></i>
                            @await Component.InvokeAsync("Language", new { path = "BODY:BUTTON:RESET" })
                        </button>
                        <a href='@Url.Action("Index", Model.ControllerName, Model.model)' class="btn btn-yellow">
                            <i class="ace-icon fa fa-chevron-circle-left bigger-110"></i>
                            @await Component.InvokeAsync("Language", new { path = "BODY:BUTTON:BACKTOLIST" })
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.pull-left -->
        </div><!-- /.ace-settings-box -->
    </div>
}

@if (Model.ActionName == "Update")
{
    <div class="ace-settings-container" id="ace-settings-container" style="position: fixed; top: 155px;">
        <div class="btn btn-app btn-xs btn-grey ace-settings-btn open" id="ace-settings-btn">
            <i class="ace-icon fa fa-cog bigger-130"></i>
        </div>

        <div class="ace-settings-box clearfix open" id="ace-settings-box">
            <!-- /.pull-left -->
            <div class="bg-rightbox">
                <div class="clearfix lineButton">
                    <div class="col-md-12 input-group">
                        <button class="btn btn-info" type="submit">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            @await Component.InvokeAsync("Language", new { path = "BODY:BUTTON:COMPLETED" })
                        </button>
                        <button class="btn btnReset" type="reset">
                            <i class="ace-icon fa fa-undo bigger-110"></i>
                            @await Component.InvokeAsync("Language", new { path = "BODY:BUTTON:RESET" })
                        </button>
                        <a href='@Url.Action("Index", Model.ControllerName, Model.model)' class="btn btn-yellow">
                            <i class="ace-icon fa fa-chevron-circle-left bigger-110"></i>
                            @await Component.InvokeAsync("Language", new { path = "BODY:BUTTON:BACKTOLIST" })
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.pull-left -->
        </div><!-- /.ace-settings-box -->
    </div>

}

Kztek_Web/Views/Shared/Partials/FooterPartial.cshtml
<div class="footer">
				<div class="footer-inner">
					<div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">@await Component.InvokeAsync("Website")</span>
							Application &copy; 2013-2014
						</span>

						&nbsp; &nbsp;
						<span class="action-buttons">
							<a href="#">
								<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-rss-square orange bigger-150"></i>
							</a>
						</span>
					</div>
				</div>
			</div>